name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nitish888/compressor-app:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 65.0.71.191  # Your EC2 instance's IP address
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying new version..."
            docker pull nitish888/compressor-app:latest
            docker stop $(docker ps -q --filter ancestor=nitish888/compressor-app:latest) || true
            docker rm $(docker ps -aq --filter ancestor=nitish888/compressor-app:latest) || true
            docker run -d -p 80:8080 nitish888/compressor-app:latest
            echo "Deployment complete."